### ISSUE TITLE
Add runtime creation to handle_server_fns() and add request/response processing

### ISSUE THREAD

**Issue by benwis** [fermyon/leptos-spin#14]
The handle_server_fns() method doesn't create a Runtime, which works, but means people won't be able to use the context to get the incoming request or pass ResponseOptions to change the returned status code or headers.

I'm happy to do this work, just want to lay out the issues here

**Comment by itowlson** [comment]
Thanks.  If you don't mind doing it, I think it would be useful for me to see what a knowledgeable person does; otherwise, I can have a crack at it and learn by being reviewed!

**Comment by benwis** [comment]
@itowlson I'm closing this as well since it's mostly done
