### ISSUE TITLE
Leptos 0.6 support 

### ISSUE THREAD

**Issue by benwis** [fermyon/leptos-spin#16]
We've released the leptos-0.6-beta, which will soon be our current release. This comes with changes to server_fns and changes to handle_server_fns(). I've opened
Issue: 2216 on Leptos to readd the function you're using, and then we'll need to change  https://github.com/leptos-rs/leptos/issues/2212

Happy to help with this

**Comment by diversable** [comment]
FYI - Leptos 0.6 is now out of Beta and into [a full production release](https://github.com/leptos-rs/leptos/releases/tag/v0.6.3). 

Perhaps now would be a good time to start looking into updating the `leptos-spin` integration...? Once this is complete, I'll update the Leptos Spin starter template to Leptos-v0.6 as well; it'd be nice to keep the leptos-spin starter in line with the other Leptos starter kits. 

Let me know when you get some time to look into this, @itowlson & @karthik2804 - we'd be happy to help from the Leptos side of things when you're available :)

**Comment by benwis** [comment]
I'm working on the update now, I'll poke you when it's ready

**Comment by benwis** [comment]
With the commit merged and the release imminent, we can close this issue.
